### ISSUE TITLE
Checklist for the assignment - check before deadline!

### ISSUE THREAD

**Issue by annakvern** [Krnsand/projekt-2#5]
Inlämningsuppgift2( Gruppuppgift) 
Ni ska tillsammans välja en hemsida som ni vill förbättra med hjälp av HTML och CSS. 

- [ ] Målet är att hemsidan ska bli mer tillgänglig och få en mer användarvänlig design än tidigare. 
- [ ] Hemsidan ska innehålla 2-4sidor och vara responsiv. 
- [ ] Hemsidan ska även ha någon dynamisk funktionalitet som förbättrar användarupplevelsen.
- [ ] Bilderkan sparas ner och användas i skoluppgiften och endast i skoluppgiften.
- [ ] Ta print screens påhemsidan, det kan hända att hemsidan uppdateras under uppgiftens gång. Ta print screens i alla enheter som ni väljer att använda er av, till exempel Mobil –Padda –Dator.
- [ ] Arbeta tillsammas och bestäm vad som behöver göras, skapa mindre uppgifter och fördela dem så ni arbeta med olika saker. Detta underlättar arbetet i GitHub. Tips, skapa en ny branch för varje uppgift och merga in den i huvudkoden när den är helt klar!
- [ ] Använd ramverk vid behov om ni vill, ej krav i uppgiften.
- [ ] Endast de filer ni arbetar med och använder i projektet ska finnas i repot på GitHub. Det ska vara rensat och klart innan inlämning. Repot ska vara rootoch innehålla era filer. Filer som inte använs eller tillhör projektet ska inte finnas irepot.
- [ ] Ni får inteanvända någon hemsida som har använts i Inlämningsuppgift 1. Inte helleren hemsida från enoffentlig aktör (kommun, myndighet, skola, osv) på grund av att de redan ska vara tillgängliga.
- [ ] Redovisning av arbetet sker på plats i skolan: Tisdag24september 09:00-16:00
- [ ] Inlämning•Deadline: Måndag23september 17:00. Koden laddas upp på GitHub. Inlämning sker på plattformen It’s Learning, lämna in:oLänk till erfärdiga Inlämningsuppgift 2 på GitHub och Länk till hemsidan ni förbättrar och Print screens på hemsidan ni förbättrar. 

**### Betygskriterie Godkänt (G):**
- [ ] Hemsidan ska innehålla logotyp, navigering, semantisk korrekt HTMLoch sidfot. 
- [ ] Menyn ska innehålla korrekt utformade länkar som leder till repektive sida(2-4 sidor).
- [ ] Responsiv –Hemsidan ska vara responsiv, anpassad efter olika skärmstorlekar, ha minst en breakpoint = två skärmstorlekar, till exempel Mobil –Dator.
- [ ] Dynamisk funktionalitet –Med hjälp av JavaScript,CSS Animationereller CSS Transitionsska hemsidan ha minst endynamisk funktionalitet.
- [ ] Tillgänglighet –Hemsidan ska vara tillgänglig. Hemsidan ska även vara testad på minst ettsätt(till exempel automatiska verktyg, användartestningoch manuellt test).oBerätta mer om detta under redovisningen.
- [ ] GitHub –Ni ska arbeta med GitHub under hela projektets gång, historik finns att titta på.

Väl Godkänt (VG):
- [ ] Allt för G-kriterie. 
- [ ] Responsiv –Hemsidan ska vara responsiv, anpassad efter olika skärmstorlekar, ha minst tvåbreakpoint = tre skärmstorlekar, till exempel Mobil –Padda -Dator.
- [ ] Menyn -Hemsidan har en fungerande mobil-och desktopmeny. Det ska finnas 2 olika menyer som är olika utformade. En padda kan till exempel ha antingen mobilmeny eller en desktopmeny. Vilket som passar bäst in på er sida väljer ni själva.
- [ ] Dynamisk funktionalitet –Med hjälp av JavaScript, CSS Animationer eller CSS Transitions ska hemsidan ha minst **tre** dynamiska funktionaliteter.
- [ ] SCSS –Använd tekniken SCSS/Sass för styling under projektets gång.
- [ ] Tillgänglighet –Hemsidan ska vara tillgänglig. Hemsidan ska även vara testad på minst tvåsätt (till exempel automatiska verktyg, användartestningoch manuellt test). Beskriv mer utförligt om detta under redovisningen.
- [ ] Arbeta självständigt (inom gruppen) under hela projektets gång, visa att ni kan hantera problemlösning och ta egna beslut. Ni får självklart fråga om hjälp!
